[feature/lesson_22] Homework: cucumber+selenide
Nadya101/BookingCom pull request #1
Opened 2021-12-19 15:14 UTC by Nadya101

2021-12-20 20:07 UTC, vchesnakoutest requested changes

2021-12-20 20:07 UTC, vchesnakoutest commented on src/test/java/steps/BookingSteps.java
> +    @Given("User is looking for hotels in {string} city")
добавь отступ перед @Given

2021-12-20 20:07 UTC, vchesnakoutest commented on src/test/java/steps/BookingSteps.java
> +    String city ;
после city лишний пробел

2021-12-20 20:07 UTC, vchesnakoutest commented on src/test/java/steps/HotelSteps.java
> +        open("https://www.booking.com/searchresults.en-gb.html");
во фреймворке 2 раза повторяется https://www.booking.com, соотв. лучше выносить в константу )

2021-12-20 20:07 UTC, vchesnakoutest commented on src/test/java/steps/HotelSteps.java
> +        String ratingXpath = "//*[contains(text(), '" +hotel+ "')]/ancestor::div[@data-testid='property-card']//div[@class='_9c5f726ff bd528f9ea6']";
@class='_9c5f726ff bd528f9ea6' - локатор конечно не самый лучший :) желательно искать что-то более конкретное и стабильное

2021-12-21 12:12 UTC, Nadya101 commented on src/test/java/steps/HotelSteps.java
> +        String ratingXpath = "//*[contains(text(), '" +hotel+ "')]/ancestor::div[@data-testid='property-card']//div[@class='_9c5f726ff bd528f9ea6']";
поменяла на :  "//*[contains(text(), '" + hotel + "')]/ancestor::div[@data-testid='property-card']//div[contains(@aria-label,'Scored')] ";

2021-12-21 12:13 UTC, merged